@AppFileSync.Api_HostAddress = http://localhost:5282

GET {{AppFileSync.Api_HostAddress}}/healthz
Accept: application/json

###

GET {{AppFileSync.Api_HostAddress}}/v1/apps
Accept: application/json
Authorization: Bearer <access-token>

###
