// <auto-generated />
using System;
using AppFileSync.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppFileSync.Api.Data.Migrations
{
    [DbContext(typeof(AppFileSyncDbContext))]
    [Migration("20260508154615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppFileSync.Api.Domain.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_subject");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSubject", "AppId", "Id")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("AppFileSync.Api.Domain.FileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CipherHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cipher_hash");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_device_id");

                    b.Property<byte[]>("EncryptedMetadata")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_metadata");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("SyncedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.HasKey("Id");

                    b.HasIndex("SyncedFileId", "Revision")
                        .IsUnique();

                    b.ToTable("file_versions", (string)null);
                });

            modelBuilder.Entity("AppFileSync.Api.Domain.KeyEnvelope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<byte[]>("EncryptedAppKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_app_key");

                    b.Property<int>("EnvelopeVersion")
                        .HasColumnType("integer")
                        .HasColumnName("envelope_version");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_subject");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSubject", "AppId", "DeviceId", "EnvelopeVersion");

                    b.ToTable("key_envelopes", (string)null);
                });

            modelBuilder.Entity("AppFileSync.Api.Domain.RegisteredApp", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxPlaintextBytes")
                        .HasColumnType("integer")
                        .HasColumnName("max_plaintext_bytes");

                    b.Property<string>("OidcClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oidc_client_id");

                    b.HasKey("AppId");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("AppFileSync.Api.Domain.SyncedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_id");

                    b.Property<long>("ChangeSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("change_sequence");

                    b.Property<string>("CipherHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cipher_hash");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<int>("CiphertextSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("ciphertext_size_bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedMetadata")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_metadata");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_subject");

                    b.Property<int>("PlaintextSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("plaintext_size_bytes");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSubject", "AppId", "ChangeSequence")
                        .IsUnique();

                    b.HasIndex("OwnerSubject", "AppId", "FileId")
                        .IsUnique();

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("AppFileSync.Api.Domain.FileVersion", b =>
                {
                    b.HasOne("AppFileSync.Api.Domain.SyncedFile", "SyncedFile")
                        .WithMany("Versions")
                        .HasForeignKey("SyncedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncedFile");
                });

            modelBuilder.Entity("AppFileSync.Api.Domain.SyncedFile", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
